# Site settings
title: Fablab for Kids
email: info@fablabforkids.it
description: > # this means to ignore newlines until "baseurl:"
  Fablab for kids, percorsi didattici per giovani inventori.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Gems
# plugins_dir: [jekyll-paginate]
gems: [jekyll-paginate]

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"
