markdown: kramdown
permalink: pretty
baseurl: #/fablabforkids
exclude: ['README.md']

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-78293879-1'
